version: "3.8"
services:
 db :
  image: postgres:latest
  container_name: PostgresAirBnb
  env_file:
   - variables.env
  ports:
   - "5432:5432"
 web:
    container_name: WebAirBnb
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - variables.env
    depends_on:
      - db
  
 server:
    container_name: ServerAirBnb
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    ports:
      - 5000:5000
    env_file:
      - variables.env
    depends_on:
      - db

